<a href="https://colab.research.google.com/github/Allan-Robert/Aulas_Python_20252/blob/main/Comandos_iniciais_10_11_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Comandos** iniciais em Python

In [ ]:
# Atribuição basicamente se faz com sinal de igual =
a=2
A=3
print("hello, word!", a)


hello, word! 2


In [ ]:
# Aqui no python o nome da variável começa com letra minuscula ou maiscula
# obviamente há também palavras reservadas que não poddemos usar ex print
d2=2


In [ ]:
# Objetos básicos
A=2  ## A é uma variável e 2 é um objeto do tipo int (inteiro)
type(A)
B='Boa noite'
type(B) # str (string)
C=2.34
type(C) # float (numeros reais, com casas decimais)
D=True # ou False
type(D) # boll Booleano (Verdadeiro ou falso)
E=[2,3.5,"3","oi"]
type(E) # list
F=(2,3.5,"3","oi")
type(F) # tuple não permite mudanças
G= {"nome": "Allan", "Cargo":"Professor", "Idade":25,"Formações":["A","B",3] }
type(G)

dict

$a^{m/n}=\sqrt[n](a^m) $

In [ ]:
### operações básicas
2+3  # soma
5-2  # subtraçao
5*10 # multiplicação
10/3 # Divisão
10//3 # Divisão inteira
10 % 3 # Resto da divisão
2 ** 3 # Potenciação
4 ** 0.5 # Raiz quadrada  de 4

2.0

In [ ]:
## Citando elementos em listas, tuplas e strings
l=[2,4,3,5,6,7,8,3,5]
#  0 1 2 3 4 5 6 7 8
# -9-8-7-6-5-4-3-2-1
l[5]
##
frase="Eu gosto de programar"
frase[2]

' '

In [ ]:
## Fatiamento intervalos de uma lista tupla ou string
l=[2,4,3,5,6,7,8,3,5]
l[2:] # da posição 2 em diante
l[:5] # posicoes anteriores a 5
l[-4:] # do -4 em diante
l[:-4] # do começo até o anterior ao -4
l[2:-2] # da posição 2 ate anterior ao -2

[3, 5, 6, 7, 8]

In [5]:
# Operadores booleanos Ou (or) E (and) Não (not)
A=3
B=2
C=2
### Ou basta que uma setença seja verdade para retornar True
print(A==B or A==C or B==C)
### E todas as sentenças tem que ser verdadeiras para retorna True
print(A==B and A==C and B==C)
### not é a negação de uma sentença
print(not A==B) # True
print(not B==C) # False

True
False
True
False


In [13]:
## Mémoria em python

x1=[1,2,3];x2=x1; x3=[1,2,3]

print(x1 is x2) # is se estão no mesmo local de memória
print(x1 is x3)
print(x1==x3) # comparação elemento a elemento


True
False
True


In [14]:
x1[2]=20 # o que eu altero em x1 altera em x2 e vice versa
print(x1)
print(x2)

[1, 2, 20]
[1, 2, 20]


In [16]:
## Como copiar?
x4=x1.copy()
print(x4)
print(x1 is x4)

[1, 2, 20]
False


In [25]:
## Outros comandos de listas, strings ou tuplas
A=[1,2,3]
print(len(A)) # tamanho
A.append(4) # introduz um número ao lado direito
print(A)
A.remove(2) # remove o primeiro a encontra igual
print(A)
del A[0] # deletando espeficando a posição
print(A)
A.index(4) # retonar o indice de um elemento

3
[1, 2, 3, 4]
[1, 3, 4]
[3, 4]


1

In [28]:
## Biblioteca
import math as mt # importando a biblioteca math e apelidando de mt
mt.sqrt(4)

2.0

In [31]:
### Uso do imput (imputar dados)
### Area de um circulo pi*r^2
from math import pi # importando a função pi da biblioteca math
raio=input('Informe o raio: ')
print('Área do círculo é',pi*float(raio)**2)

Informe o raio: 10
Área do círculo é 314.1592653589793


In [41]:
import numpy as np # biblioteca base do python para calculos
x = np.linspace(0,10,5) # criando sequências de tamanho 5
print(x)
y=np.arange(10,30,5) # de 10 até anterior de 30 de 5 em 5
print(y)
A=[1,2]
An=np.repeat(A,[2,3],axis=0) # repeticção elemento por elemento
print(An)
type(An)
np.tile(An,4)  # repetição de sequencia n vezes


[ 0.   2.5  5.   7.5 10. ]
[10 15 20 25]
[1 1 2 2 2]


array([1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2])

In [42]:
np.random.normal(10,1,30)

array([ 9.51874757, 10.64521637,  8.00982046,  9.50189382,  8.85644889,
       10.09368769,  9.70740447,  9.91949226, 10.05315942,  8.80620962,
        8.02408567, 11.52479161,  9.42276646, 11.37294174, 10.83623713,
        8.94414702, 10.68836399, 10.36778517, 10.46279912, 10.12398955,
       10.07065841, 10.63385594, 12.51239465,  9.9178422 , 11.84313832,
        8.7544516 , 11.14588622,  9.54573146, 10.13665995,  9.82976512])

def nomedafunção(argumento1,argumento2,...):
  r1=comandos usando argumentos
  r2=outros comandos
  ....
  return r1,r2,...


In [47]:
### Funções
def soma_mult(a,b):
  soma=a+b
  mult=a*b
  return soma,mult

Res=soma_mult(2,5)
type(Res)
A,B=soma_mult(3,4)
print(A)
print(type(A))
print(B)

7
<class 'int'>
12
